### ISSUE TITLE
Problem of starting  docker container

### ISSUE THREAD

**Issue by luashiping** [maxexcloo/Docker#14]
why you don't append '/usr/bin/supervisord'  to the end of 'docker run.............' when you starting container

**Comment by maxexcloo** [comment]
I run init scripts before firing up the processes, not sure how else to do
it...

**Comment by luashiping** [comment]
can you starting container successfully?

**Comment by maxexcloo** [comment]
Yes

**Comment by luashiping** [comment]
You run nginx with "daemon off" ,but the model mainly used during development

**Comment by maxexcloo** [comment]
Because otherwise it isn't compatible with supervisord. I'm not sure what the problem you're experiencing is.
