### ISSUE TITLE
Add docker for DNS-Tunnel?

### ISSUE THREAD

**Issue by tvvocold** [maxexcloo/Docker#18]
https://github.com/maxexcloo/DNS-Tunnel
It would be great if there is a docker support!

**Comment by maxexcloo** [comment]
This did actually exist at one point but it was quite annoying to maintain
(not to mention I never used it), maybe in future!

**Comment by tvvocold** [comment]
Cool!
We Chinese need it , it help me cross the great fire wall of China:)
Thx btw.
