### ISSUE TITLE
Cannot upload files larger than 4KB

### ISSUE THREAD

**Issue by adrian7** [maxexcloo/Docker#21]
I have an image based on `maxexcloo/nginx-php` and shared with a local directory. Everything seems to work fine but I cannot upload files over 4kb in size :( . I get the following error from nginx:

 `open() "/var/lib/nginx/body/0000000001" failed (13: Permission denied), client: 192.168.99.1, server: localhost, request: "POST /tools/upload.php HTTP/1.1", host: "192.168.99.100:32774", referrer: "http://192.168.99.100:32774/tools/upload.php"`

**Comment by maxexcloo** [comment]
It should allow it! The cap is 256 MB, can you reopen if this is still an issue?
